name: healthmate
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.3
  flutter_dotenv: ^5.2.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  flutter_local_notifications: ^18.0.1
  table_calendar: ^3.2.0
  intl: ^0.20.2
  image_picker: ^1.1.2
  getwidget: ^6.0.0
  calendar_view: ^1.4.0
  url_launcher: ^6.3.1
  timezone: ^0.10.0
  permission_handler: ^11.4.0
  app_settings: ^5.2.0
  shared_preferences: ^2.5.2
  smooth_page_indicator: ^1.2.1
  firebase_storage: ^12.4.4
  shimmer: ^3.0.0
  provider: ^6.1.2
  http: ^1.3.0
  flutter_markdown: ^0.7.6+2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assests/images/
    - assests/fonts/
    