// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['WEB_API_KEY'] ?? '',
    appId: '1:483332417256:web:563c58b5daecbedfc88b5d',
    messagingSenderId: '483332417256',
    projectId: 'healthmate-5a3d7',
    authDomain: 'healthmate-5a3d7.firebaseapp.com',
    storageBucket: 'healthmate-5a3d7.firebasestorage.app',
    measurementId: 'G-3YWTJYFD95',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['ANDROID_API_KEY'] ?? '',
    appId: '1:483332417256:android:29a3efa3c4eadb81c88b5d',
    messagingSenderId: '483332417256',
    projectId: 'healthmate-5a3d7',
    storageBucket: 'healthmate-5a3d7.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IOS_API_KEY'] ?? '',
    appId: '1:483332417256:ios:c8c9de1010236cedc88b5d',
    messagingSenderId: '483332417256',
    projectId: 'healthmate-5a3d7',
    storageBucket: 'healthmate-5a3d7.firebasestorage.app',
    iosBundleId: 'com.example.healthmate',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['MACOS_API_KEY'] ?? '',
    appId: '1:483332417256:ios:c8c9de1010236cedc88b5d',
    messagingSenderId: '483332417256',
    projectId: 'healthmate-5a3d7',
    storageBucket: 'healthmate-5a3d7.firebasestorage.app',
    iosBundleId: 'com.example.healthmate',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['WINDOWS_API_KEY'] ?? '',
    appId: '1:483332417256:web:0f6e145745a059fbc88b5d',
    messagingSenderId: '483332417256',
    projectId: 'healthmate-5a3d7',
    authDomain: 'healthmate-5a3d7.firebaseapp.com',
    storageBucket: 'healthmate-5a3d7.firebasestorage.app',
    measurementId: 'G-9SN3J4XL7J',
  );
}